### ISSUE TITLE
Robots tick possible issue

### ISSUE THREAD

**Issue by Glucocorticoid** [HaploX1/RimWorld-Miscellaneous_Source#2]
Hi. I found a suspicious code of Misc robots mod.

https://github.com/HaploX1/RimWorld-Miscellaneous_Source/blob/161374cd413443ae922a748aa17e194edded32b9/Source/AIRobot/X2_AIRobot.cs#L226

Looks like it should remove unwanted hediffs every 500 ticks. But in this case it will work every tick except of every 500th tick.

Is it works as intended?

**Comment by HaploX1** [comment]
Thanks for the info, I missed that. It will be fixed in the next build :)
