### ISSUE TITLE
Updated CE Compatibility

### ISSUE THREAD

**Issue by perkinslr** [HaploX1/RimWorld-Miscellaneous_Source#4]
Your Misc Patches for CE hasn't been re-released since 1.0.  I am happy to lift the compatibiltiy code into CE's repository so you don't have to do anything further with it, but I want to make sure there are no plans that would be significantly disrupted if it were made redundant.

**Comment by HaploX1** [comment]
Hi perkinslr,
Feel free to implement it directly in CE.
I'm not working on any compatibility patches right now and will not do so anytime soon. I just don't have the time for it.
Thank you for your work :)
Greetings
Haplo
