### ISSUE TITLE
Issue with latest update for Kitchen/Omni Bots (Robots)

### ISSUE THREAD

**Issue by acorrow** [HaploX1/RimWorld-Miscellaneous_Source#5]
Myself and others have seen in recent days/weeks the Omni and Kitchen bots seem to be refusing to do work. Upon investigation, I found some call stacks that pointed to the X2_JobGiver_Work.cs code, and upon reviewing it, I think you may have a misunderstanding of .NET reference values (or I have a misunderstanding of what you are doing here).

https://github.com/HaploX1/RimWorld-Miscellaneous_Source/commit/54f358458bc13986612304128ed5902d1a19be34#diff-69e14a214f4c0c35a6a7f9089222d2b4dabbe0e0e33f05ec8174418cd0721920

Check out line 119:

`IEnumerable<Thing> potentialWorkThings2 = potentialWorkThings;`

This creates a REFERENCE to potentialWorkThings, called potentialWorkThings2. If you change a property on `potentialWorkThings2` you are really just making a change to `potentialWorkThings`. You create a new object, but its still just a reference to the first.

It looks like later on in the code you reference it again in another context, Line 128:

`IEnumerable<Thing> potentialWorkThings3 = potentialWorkThings;`

potentialWorkThings3 = potentialWorkThings2 = potentialWorkThings. They are all just references to the same underlying object in this context.

My guess is that it just works most of the time not getting into the guts of this code block, but something about sewing does. Honestly, I spend all day debugging code in the real world, so I don't have it in me on a Saturday night to get much deeper than this, but I love this mod, and I have zero experience modding Rimworld, so I took the effort to try to quickly learn it in hopes of identifying this issue so I can get back to building bases to robots cause I love this mod.

Maybe I'm wrong with this assessment, but I suspect this is at least partly the cause here. Thanks and let me know if you need more info

**Comment by acorrow** [comment]
Ok so I guess I can at least give a simple solution (if you want to give it a try, this is all just my theory from reading the code here):

A simple way you can do what you are looking for (making a copy of an IEnumerable) is to just dump it to a List<> object. ToList() should be fairly optimized here, but I'm not TOTALLY sure the scope of this code, and how many times it is really called. But the idea being, you are likely looking to make a copy of the object.

Note: Using .ToList() you maybe want to explicitly dispose the data inside your scope here. If you don't explicitly dispose, and this is called a bunch, the Garbage collector may let it pile up for a bit and you will have performance issues. I'm not totally sure how Unity really handles Garbage collection, but I'm pretty sure it relies on the .NET FW's logic for it, so that I AM pretty familiar with. Anyway, a simple solution when you want a copy of an IEnumerable is to dump it to a list.

**Comment by acorrow** [comment]
I'm not even sure this is what the issue is FYI, just noticed this while reading the code :) Either way, I love this mod, and I want it back :)

**Comment by acorrow** [comment]
Damn it.... I found your bug...

X2_JobGiver_Work.cs
Line 152:

```
int maxCheck = 75;
```

In the context of what you are doing here, if the job giver is a field (sowing whatever) and there are MORE than 75 total possible cells with sowing jobs on them, and the one you HAPPEN to get here is out of the range of 75, you will have this happen.

This is because in your check when you are actually enumerating all the possible work for this pawn, you only ever check 75 cells. You can quickly fix this by upping that to a large(er) number. Or really, you can (Should) just have some better logic to determine:

1: Is this a field/sowing job?
2: If so, ensure that I do NOT limit my search to only 75 of the possible jobs

I can confirm this fixes the issue (upped this to 5K for my test, but I will try some more advanced logic like I said here).

Sorry about the red herrings with the equality/reference stuff, but it's still valid, just not this problem at all :D

**Comment by acorrow** [comment]
[Pull Request To Address This Issue](https://github.com/HaploX1/RimWorld-Miscellaneous_Source/pull/6/commits/1bb816019a8d61cb85a7ca6521db82689dc4e2ae)

**Comment by HaploX1** [comment]
Thanks for the bugfix. I've integrated it.
For the other issues: From my point of view a reference is not really an issue, even if I create multiple references to the same object. As long as it's released (and even if not manually done, the garbage collector will get to it eventually :) )
So.. I'll look into it a bit when I have some time, but I'm not sure I'll change it. We'll see, but thanks anyway 👍
